name: Asset size

on: [pull_request]

jobs:
  compare:
    timeout-minutes: 15
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
        with:
          fetch-depth: 0
      - uses: chrysanthos/simple-asset-size-reporter@3c86a594c400b40a4ebe6418da605a5d2755ef52 # 1.0.2
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          files: '["dist/*.js"]'
          with-same: "false"
          build-assets: "npm run install-build"
